---
title: "Exploring bike data"
author: "Alexander"
date: "20/06/2021"
output: 
  html_document:
    keep_md: true
  
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file(),echo = TRUE)

```

## Exploring the bike data characteristics

We're exploring the bike data to look at the relationship between **temperature** and **riders.**

### Step 0: Load tidyverse

```{r - load tidyverse, warning=FALSE}
library(tidyverse)
```


### Step 1: Load the bike data and look at the metadata


```{r - load bike data}
#loading bike data
bike <- read.csv("data/daily_bike_data.csv")
head(bike)
str(bike)
sort(names(bike))

```


```{r - initial graph analysis}
#Time trend of ridership

ggplot(bike,aes(x= dteday, y = cnt))+
  geom_point()

ggplot(bike,aes(x= temp, y = cnt))+
  geom_point()
```


```{r - data cleaning}
# dplyr verbs for data transformations
#   select: select columns to keep
#   filter: select rows to keep
#   mutate: transforms data while keep other columns
#   transmute: creates new columns and does not keep old columns
#   %>%: "pipe" pipes de output from one command as input for next command

bike %>% select(dteday, season, weathersit, temp, cnt)

# One way of selecting spring records

spring_bike <- filter(bike, season == "spring")

spring_bike_temp_cnt2 <- bike %>%
  filter(season == "spring") %>%
  select(temp, cnt)

#Exercise: select weathersit and cnt for all winter records

winter_bike_weathersit <- bike %>%
  filter(season == "winter") %>%
  select(weathersit, cnt)

```

```{r - Mutate and Transmute with Factors and Dates}

summary(bike$weathersit)
unique(bike$weathersit)

# Mutating a factor column for weather

bike2 <- bike %>% mutate(
    weather_fac = factor(weathersit, levels = c(1,2,3,4), labels = c("Clear", "Cloudy", "Rainy", "Heavy Rain"))
  )

# Converting to and from dates

bike_dates <- bike %>% transmute(
  instant,
  date_date = as.Date(dteday),
  date_char = as.character(dteday),
  date_num = as.numeric(date_date)
)

# Additional filtering and selecting

bike %>% select(dteday, cnt)

keep_vars <- c("dteday","cnt","temp")
bike %>% select(all_of(keep_vars))

bike %>% filter(season != "spring") %>% select(season) %>% distinct()

bike %>% filter(season == "summer" | season == "winter")

## More dplyr verbs
# summarise: summary of multiple rows for a col/variable
# group_by: perform a operation separately for each group

bike2 %>% summarise(
  temp_mean = mean(temp),
  cnt_mean = mean(cnt),
  cnt_sum = sum(cnt)
)

bike2 %>%
  group_by(season) %>% 
  summarise(
    temp_mean = mean(temp),
    ride_sum = sum(cnt)
    )

# What are the season definitions?
sort(names(bike))
bike %>% select(season, mnth) %>% distinct()

#Create new season with metereological definitions

bike3 <- bike2 %>%
  mutate(
    season2 = 1 * (mnth %in% c("December", "January", "February")) + 2 * (mnth %in% c("March", "April", "May")) + 3 * (mnth %in% c("June", "July", "August")) + 4 * (mnth %in% c("September", "October", "November"))
  ) %>%
  mutate(
    season2 = factor(season2, levels = 0:4, labels = (c("Unknown", "Winter", "Spring", "Summer", "Fall"))
  ))

bike3 %>%
  group_by(season2) %>% 
  summarise(
    temp_mean = mean(temp),
    ride_sum = sum(cnt)
    )

```

```{r - Facesetting in ggplot}

bike3 %>%
  ggplot() +
   geom_point(aes(x = temp, y = cnt)) +
   geom_smooth(aes(x = temp, y = cnt), method = "lm", formula = y ~ poly(x,2))+
   facet_wrap(~ season2)
  

```

```{r - More data transformations}
## Pivoting wider to long and longer to wide
# Long to wide: data in multiple columns
# Wide to ling: data in one column, classifier in other columns
# tidyr is the package that allows transformations

months <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")

tidybike <- bike3 %>%
  select(yr, mnth, temp, cnt) %>%
  mutate(month = factor(mnth, levels = months)) %>%
  group_by(yr, month) %>%
  summarise(temp_mean = mean(temp),
            rides = sum(cnt))

## Tidyr functions for long to wide:

# pivot_wider

tidybike %>% 
  select(-rides) %>%
  pivot_wider(values_from = temp_mean, names_from = month, names_prefix = "temp_")

#spread

tidybike %>% 
  select(-rides) %>%
  spread(value = temp_mean, key = month)

## Exercise: do the same, but widening for rides

#pivot_wider

rides <- tidybike %>% 
  select(-temp_mean) %>%
  pivot_wider(values_from = rides, names_from = month, names_prefix = "rides_") %>%
  rename_with(tolower) %>%
  rename(year = yr)

## Going from wide to long
# pivot_longer
# gather

rides %>% gather(key = "month", value = "rides", -year)

rides %>%
  select(year, rides_january, rides_february) %>%
  pivot_longer(names_to = "month", cols = c("rides_january", "rides_february"), values_to = "rides") %>%
  mutate(month = substr(month, 7, nchar(month)))

```



